console.log()
console.log('\x1b[32m――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――')
console.log('\x1b[36mThank you for installing Discord Economy Super!')
console.log('\x1b[32m――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――')
console.log('\x1b[32mIf you have any questions or need help, join the Support Server:')
console.log('\x1b[34mhttps://discord.gg/afUTRzfb')
console.log('\x1b[32m――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――\x1b[37m')
console.log()