declare type EconomyErrorCodes =
    'INVALID_TYPE' |
    'INVALID_CACHING_IDENTIFIERS' |
    'INVALID_CACHE_ITEM_NAME' |
    'UNKNOWN_ERROR' |
    'ITEM_PROPERTY_INVALID' |
    'INVALID_INPUT' |
    'PARAMETER_NOT_SPECIFIED' |
    'OLD_NODE_VERSION' |
    'NO_DISCORD_CLIENT' |
    'ROLE_NOT_FOUND' |
    'PURCHASES_HISTORY_DISABLED' |
    'SETTINGS_KEY_INVALID' |
    'READONLY_PROPERTY' |
    'INVALID_PROPERTY' |
    'CURRENCY_NOT_FOUND' |
    'INVALID_ERROR_CODE' |
    'MODULE_NOT_READY' |
    'NO_CONNECTION_DATA'

export = EconomyErrorCodes