#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Run these additional scripts to continue:"
echo "-------------------------------------------"
echo

echo "Commit changes to public repository:"
echo "bash ./.husky/scripts/commit-to-public.sh"

echo
echo "Deploy the documentation:"
echo "bash ./.husky/scripts/deploy-docs.sh"
echo
